#!/bin/bash 
 
apt install feh -y
pip3 install pywal 
apt install imagemagick -y

wal -i temp.jpg

echo "(cat ~/.cache/wal/sequences &)"

#add_ifnt "(cat ~/.cache/wal/sequences &)"

ln -s ~/.cache/wal/colors-konsole.colorscheme ~/.local/share/konsole

echo "Konsole: edit current profile > use color scheme generated by pywal"
